[2022-02-09 12:41:52,164] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_print.task_1_data_file_cleanup manual__2022-02-09T02:46:33.420450+00:00 [queued]>
[2022-02-09 12:41:52,250] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_print.task_1_data_file_cleanup manual__2022-02-09T02:46:33.420450+00:00 [queued]>
[2022-02-09 12:41:52,251] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 12:41:52,251] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-09 12:41:52,251] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 12:41:52,351] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): task_1_data_file_cleanup> on 2022-02-09 02:46:33.420450+00:00
[2022-02-09 12:41:52,354] {standard_task_runner.py:52} INFO - Started process 26177 to run task
[2022-02-09 12:41:52,358] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test_print', 'task_1_data_file_cleanup', 'manual__2022-02-09T02:46:33.420450+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp7en7arfe', '--error-file', '/tmp/tmpsxjzt9c5']
[2022-02-09 12:41:52,358] {standard_task_runner.py:77} INFO - Job 39: Subtask task_1_data_file_cleanup
[2022-02-09 12:41:52,536] {logging_mixin.py:109} INFO - Running <TaskInstance: test_print.task_1_data_file_cleanup manual__2022-02-09T02:46:33.420450+00:00 [running]> on host workspace-1-v1-57c59dfd9c-lcldg
[2022-02-09 12:41:52,794] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/xcom.py:323 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-02-09 12:41:52,843] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/renderedtifields.py:126 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-02-09 12:41:52,901] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/renderedtifields.py:162 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2022-02-09 12:41:52,908] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/renderedtifields.py:159 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-02-09 12:41:52,946] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akj00173@gmail.com
AIRFLOW_CTX_DAG_OWNER=someone
AIRFLOW_CTX_DAG_ID=test_print
AIRFLOW_CTX_TASK_ID=task_1_data_file_cleanup
AIRFLOW_CTX_EXECUTION_DATE=2022-02-09T02:46:33.420450+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-09T02:46:33.420450+00:00
[2022-02-09 12:41:52,948] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-09 12:41:52,949] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /workspace/tracker/code/track_chicken_date_gpu.py "/workspace/nas-data/Animal/chicken_video/"$(date -d "yesterday" +%Y%m%d)']
[2022-02-09 12:41:52,967] {subprocess.py:85} INFO - Output:
[2022-02-09 12:42:13,754] {local_task_job.py:211} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-02-09 12:42:13,758] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 26177. PIDs of all processes in the group: [26181, 26177]
[2022-02-09 12:42:13,758] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 26177
[2022-02-09 12:42:13,758] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-02-09 12:42:13,758] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2022-02-09 12:42:13,810] {process_utils.py:70} INFO - Process psutil.Process(pid=26177, status='terminated', exitcode=0, started='12:41:52') (26177) terminated with exit code 0
[2022-02-09 12:42:14,184] {process_utils.py:70} INFO - Process psutil.Process(pid=26181, status='terminated', started='12:41:52') (26181) terminated with exit code None
